### ISSUE TITLE
Issue in latest version 1.3.0

### ISSUE THREAD

**Issue by kushagrasharmait** [alexjeffburke/rightimage#5]
while using  createimagepipeline method  in the  latest version of rightimage module (1.3.0) we are getting an error **"Unsupported input 'undefined' of type undefined when also providing options of type object"**  we have't made any changes in inputs  and this functionality was working fine in the previous versions of rightimage module.

![Screenshot from 2022-03-22 14-23-08](https://user-images.githubusercontent.com/44570880/159443252-ba1960c0-3e3b-4b8b-b49f-624586cc8e42.png)
![Screenshot from 2022-03-22 14-22-36](https://user-images.githubusercontent.com/44570880/159443263-d154a53c-41a3-4f9c-9432-33c2fdc0f013.png)
![Screenshot from 2022-03-22 14-21-34](https://user-images.githubusercontent.com/44570880/159443266-eab7b454-ce2d-4454-9da2-2505c5c809dc.png)

**Comment by alexjeffburke** [comment]
Hi,

Appreciate the report - I won’t be near a computer for a while so can’t look at this too deeply until I am again.

That said, I had another peek over the changes that went into 1.3.0 and still can’t see anything that would lead to this. I’ve also tried to find that message you noted in bold in the relevant code but can’t see that exact wording anywhere, so am wondering if it’s actually bubbling up from one of the image libs.

Could you show me the stack trace from the error? Might help to narrow things down - if sharing that in public is an issue then am happy to arrange a one time link or similar. And does this happen for all input images or just this one?

Some additional questions:
* can you confirm the stream being passed into rightimage is valid?
* if so, is the input a test image or user data?
* the 1.3 upgrade was a drop in for 1.2 with the only difference being support for maxInputPixels/maxOutputPixels - can you double check no other versions of dependencies changed during installation and that simply dropping 1.2 back in with the same erroring data makes it issue go away?

Thanks, Alex J Burke.

**Comment by alexjeffburke** [comment]
Hi again,

I’ve not heard back on any of those questions I posed and I can’t cause the issue here so I don’t think I can do much else. As such I’m going to close this issue - if you have a chance to gather any of that information feel free to throw up the detail and reopen it.

Alex

**Comment by abhi11210646** [comment]
HI Alex, 

This issue arose due to conflicting versions of rightImage moduel. In parent repository rightImage version was 1.3.0 but in child repository it was 0.7.2(old one). Sorry for Inconvenience. Issue can be closed forever. 

Thanks
